langchain:
  api-key: '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'
  timeout: 30

spring:
  datasource:
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5433/vector_store
  ai:
    openai:
      api-key: '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'
