langchain:
  api-key: ${OPENAI_API_KEY}
  timeout: 30

spring:
  datasource:
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5433/vector_store
  devtools:
    restart:
      exclude: "**/uploads/**/*"
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
